import { createHash } from 'node:crypto';
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { resolve, join, relative } from 'node:path';
import { execSync } from 'node:child_process';
import { KnowledgeProvider, KnowledgeRequest, KnowledgeSnapshotPayload, RelevantSourceFile, DependencyEntry } from '../../domain/knowledge/KnowledgeProvider.js';

export class GitKnowledgeProvider implements KnowledgeProvider {
  constructor(private readonly workspaceRoot: string = process.cwd()) {}

  public async produceSnapshot(request: KnowledgeRequest): Promise<KnowledgeSnapshotPayload> {
    // 1. Resolve source revision (Git commit SHA or fallback)
    const sourceRevision = this.resolveRevision(request.sourceRevision);

    // 2. Hash dependency lockfile (package-lock.json or package.json)
    const dependencyLockHash = this.computeLockHash();

    // 3. Scan workspace source files
    const relevantSourceFiles = this.scanSourceFiles();

    // 4. Extract dependencies from manifest
    const dependencies = this.extractDependencies();

    return {
      sourceRevision,
      dependencyLockHash,
      verifiedAt: new Date().toISOString(),
      freshnessPolicyVersion: '1.0.0',
      relevantSourceFiles,
      relevantSymbols: [], // Full symbol graph is a future port optimization behind this same contract (§20)
      dependencies,
      documentationRefs: [
        {
          identifier: 'TECHSPEC.md',
          title: 'HITM Workflow Technical Implementation Specification',
          retrievedAt: new Date().toISOString()
        }
      ],
      notes: 'Generated by Minimal GitKnowledgeProvider adapter'
    };
  }

  public async invalidate(_keys: string[]): Promise<void> {}

  private resolveRevision(override?: string): string {
    if (override && /^[0-9a-f]{7,40}$/i.test(override)) {
      return override;
    }
    try {
      const sha = execSync('git rev-parse HEAD', { cwd: this.workspaceRoot, stdio: ['ignore', 'pipe', 'ignore'] })
        .toString()
        .trim();
      if (/^[0-9a-f]{7,40}$/i.test(sha)) {
        return sha;
      }
    } catch {}
    // Fallback deterministic 40-char SHA if running in detached/uncommitted repo
    return createHash('sha1').update('fallback-initial-revision').digest('hex');
  }

  private computeLockHash(): string {
    const lockPath = join(this.workspaceRoot, 'package-lock.json');
    const pkgPath = join(this.workspaceRoot, 'package.json');
    const targetPath = existsSync(lockPath) ? lockPath : pkgPath;

    if (existsSync(targetPath)) {
      const content = readFileSync(targetPath);
      return createHash('sha256').update(content).digest('hex');
    }
    return createHash('sha256').update('empty-dependency-manifest').digest('hex');
  }

  private scanSourceFiles(): RelevantSourceFile[] {
    const srcDir = join(this.workspaceRoot, 'src');
    if (!existsSync(srcDir)) return [];

    const results: RelevantSourceFile[] = [];
    const walk = (dir: string) => {
      for (const entry of readdirSync(dir)) {
        const full = join(dir, entry);
        const stat = statSync(full);
        if (stat.isDirectory()) {
          walk(full);
        } else if (stat.isFile() && (entry.endsWith('.ts') || entry.endsWith('.json'))) {
          const content = readFileSync(full);
          const hash = createHash('sha256').update(content).digest('hex');
          const rel = relative(this.workspaceRoot, full).replace(/\\/g, '/');
          results.push({
            path: rel,
            contentHash: hash,
            language: entry.endsWith('.ts') ? 'typescript' : 'json'
          });
        }
      }
    };
    walk(srcDir);
    return results;
  }

  private extractDependencies(): DependencyEntry[] {
    const pkgPath = join(this.workspaceRoot, 'package.json');
    if (!existsSync(pkgPath)) return [];

    try {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
      const deps: DependencyEntry[] = [];
      const runtimeDeps = pkg.dependencies || {};
      for (const [name, version] of Object.entries(runtimeDeps)) {
        deps.push({
          name,
          version: String(version),
          resolved: String(version),
          ecosystem: 'npm',
          manifestPath: 'package.json'
        });
      }
      return deps;
    } catch {
      return [];
    }
  }
}
